/**
 * GitHub App PR Comment Bot
 * 
 * This module handles posting and updating comments on GitHub pull requests
 * with preview links and visual diff information.
 */

// Import types to avoid TypeScript errors
import type { Octokit } from '@octokit/rest';
import type { createAppAuth as CreateAppAuthType } from '@octokit/auth-app';
import * as fs from 'fs';
import defaultConfig from './config.js';
import { getGitHubPrivateKey, getOctokitAuthOptions } from './key-utils.js';

// Dynamically import the modules to avoid TypeScript errors
let OctokitModule: any;
let AuthAppModule: any;

// Initialize the modules
async function initModules() {
  try {
    OctokitModule = await import('@octokit/rest');
    AuthAppModule = await import('@octokit/auth-app');
  } catch (error) {
    console.error('Error importing Octokit modules:', error);
  }
}

// Call the initialization function
initModules();

// Interface for PR comment parameters
interface PrCommentParams {
  org: string;
  repo: string;
  prNumber: number;
  branch: string;
  sha: string;
  url: string;
  diffSummary?: string;
}

/**
 * Create an authenticated Octokit instance for GitHub API calls
 */
async function createOctokitClient(installationId: number): Promise<any> {
  try {
    // Make sure modules are loaded
    if (!OctokitModule || !AuthAppModule) {
      await initModules();
    }
    
    // Create the authentication function using centralized auth options
    const auth = AuthAppModule.createAppAuth(getOctokitAuthOptions());
    
    // Create an installation token
    const { token } = await auth({
      type: 'installation',
      installationId,
    });
    
    // Return an authenticated Octokit instance
    return new OctokitModule.Octokit({ auth: token });
  } catch (error) {
    console.error('Error creating Octokit client:', error);
    throw new Error('Failed to authenticate with GitHub');
  }
}

/**
 * Get the installation ID for a repository
 */
async function getInstallationId(org: string, repo: string): Promise<number> {
  try {
    // Make sure modules are loaded
    if (!OctokitModule || !AuthAppModule) {
      await initModules();
    }
    
    // Create the authentication function using centralized auth options
    const auth = AuthAppModule.createAppAuth(getOctokitAuthOptions());
    
    // Create an app token
    const { token } = await auth({ type: 'app' });
    
    // Create an Octokit instance with the app token
    const octokit = new OctokitModule.Octokit({ auth: token });
    
    // Get the installation for this repository
    const { data: installations } = await octokit.apps.listInstallations();

    type Installation = typeof installations[number];

    console.log('[GH] installations seen:', installations.map((inst: Installation) => inst.account?.login));
    
    const installation = installations.find((inst: Installation) =>
      inst.account?.login?.toLowerCase() === org.toLowerCase()
    );
    
    if (!installation) {
      throw new Error(`No installation found for organization ${org}`);
    }
    
    return installation.id;
  } catch (error) {
    console.error('Error getting installation ID:', error);
    throw new Error('Failed to get installation ID');
  }
}

/**
 * Generate the comment body with preview link and diff summary
 */
function generateCommentBody(params: PrCommentParams): string {
  const { branch, sha, url, diffSummary } = params;
  
  let comment = `## 🚀 GridLabs Preview
  
**Branch:** \`${branch}\`
**Commit:** \`${sha.substring(0, 7)}\`

### 🔍 Preview Link
👉 [View the preview](${url})

`;

  if (diffSummary) {
    comment += `### 📊 Visual Changes
${diffSummary}

`;
  }

  comment += `---
*This preview was automatically generated by the GridLabs GitHub App.*
*[Learn more about GridLabs Cloud](https://github.com/gridlabs/gridlabs/blob/main/CLOUD.md)*`;

  return comment;
}

/**
 * Find an existing comment by the bot on the PR
 */
async function findExistingComment(
  octokit: Octokit,
  org: string,
  repo: string,
  prNumber: number
): Promise<number | null> {
  try {
    // Get all comments on the PR
    const { data: comments } = await octokit.issues.listComments({
      owner: org,
      repo,
      issue_number: prNumber,
    });
    
    // Look for a comment that contains our signature
    const botComment = comments.find(comment => 
      comment.body.includes('*This preview was automatically generated by the GridLabs GitHub App.*')
    );
    
    return botComment ? botComment.id : null;
  } catch (error) {
    console.error('Error finding existing comment:', error);
    return null;
  }
}

/**
 * Post or update a comment on a GitHub pull request
 */
export async function postPrComment(params: PrCommentParams): Promise<void> {
  const { org, repo, prNumber } = params;
  
  try {
    // Get the installation ID for this repository
    const installationId = await getInstallationId(org, repo);
    
    // Create an authenticated Octokit client
    const octokit = await createOctokitClient(installationId);
    
    // Generate the comment body
    const commentBody = generateCommentBody(params);
    
    // Find an existing comment by the bot
    const existingCommentId = await findExistingComment(octokit, org, repo, prNumber);
    
    if (existingCommentId) {
      // Update the existing comment
      await octokit.issues.updateComment({
        owner: org,
        repo,
        comment_id: existingCommentId,
        body: commentBody,
      });
      
      console.log(`Updated comment #${existingCommentId} on PR #${prNumber} in ${org}/${repo}`);
    } else {
      // Create a new comment
      const { data: comment } = await octokit.issues.createComment({
        owner: org,
        repo,
        issue_number: prNumber,
        body: commentBody,
      });
      
      console.log(`Created comment #${comment.id} on PR #${prNumber} in ${org}/${repo}`);
    }
  } catch (error: unknown) {
    const err = error as Error;
    console.error('Error posting PR comment:', err);
    throw new Error(`Failed to post PR comment: ${err.message || 'Unknown error'}`);
  }
}
